version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ai_social_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ai_social_frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend
    env_file:
      - .env
    restart: always
